# Generated by Django 2.2.3 on 2019-07-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=200, verbose_name='Subtitulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('costo', models.IntegerField(verbose_name='Costo')),
                ('imagen', models.ImageField(upload_to='services', verbose_name='Imagen')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('edicion', models.DateField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-creacion'],
            },
        ),
    ]
