# Generated by Django 2.2.3 on 2019-07-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicado/Oculto'),
        ),
        migrations.AddField(
            model_name='service',
            name='index',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar en el inicio?'),
        ),
    ]
