# Generated by Django 2.2.3 on 2019-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190728_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mensualidad',
            field=models.IntegerField(verbose_name='Mensualidad'),
        ),
    ]
