# Generated by Django 2.2.3 on 2019-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='horarios',
        ),
        migrations.AddField(
            model_name='service',
            name='jornada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jornada(s)'),
        ),
    ]
