# Generated by Django 2.2.3 on 2019-07-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20190728_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='service',
            name='descripcion',
            field=models.CharField(default='jkfhdgjkshdfkjghkdfjg', max_length=200, verbose_name='Descripción'),
        ),
    ]
