# Generated by Django 2.2.3 on 2019-07-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190729_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
