# Generated by Django 2.2.3 on 2019-07-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20190729_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
    ]
