# Generated by Django 2.2.3 on 2019-07-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190728_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
    ]
