# Generated by Django 2.2.3 on 2019-07-28 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190728_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion'),
        ),
    ]
