# Generated by Django 2.2.3 on 2019-07-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190729_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='SOME STRING', verbose_name='Slug/Url'),
        ),
    ]
