# Generated by Django 2.2.3 on 2019-08-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_colegio_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='historia',
            field=models.TextField(verbose_name='Historia'),
        ),
    ]
