# Generated by Django 2.2.3 on 2019-08-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='apellido',
            field=models.CharField(max_length=15, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='grados',
            field=models.CharField(max_length=20, verbose_name='Grados a los que enseña'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='informacion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Información'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre'),
        ),
    ]
